public function kolcsonzesTry($copy_id)
    {
        $user = Auth::user();
        try {
            $pontok = DB::table('lendings')
                ->where('user_id', $user->id)
                ->sum('notice');
                echo $pontok;

            if ($pontok <= 3) {
                DB::table('lendings')->insert([
                    'user_id' => $user->id,
                    'copy_id' => $copy_id,
                    'start' => date(now()),
                    'extension' => 0,
                    'notice' => 0,
                ]);
            }else{
                echo "Túl sok figyelmeztetésed van!";
            }
        } catch (QueryException $e) {

            if ($e->errorInfo[1] == 1062) {
                echo "A rekord már létezik a táblában.";
            } else {

                echo "Hiba történt: " . $e->getMessage();
            }
        }
    }